application: commitconversations
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /tasks/.*
  script: tasks_handler.py
  login: admin
- url: /scripts
  static_dir: scripts
- url: /styles
  static_dir: styles
- url: /css
  static_dir: bootstrap/css
- url: /img
  static_dir: bootstrap/img
- url: /js
  static_dir: bootstrap/js
- url: /styles
  static_dir: styles
- url: /api/.*
  script: web_api.py
- url: /.*
  script: root_handler.py
